sudo: required
language: rust
rust:
- nightly
branches:
  only:
    - bench
before_install:
  - sudo apt-get install libcairo2-dev
  - sudo apt-get install libpango1.0-dev
  - curl -L https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.6/gnuplot-5.0.6.tar.gz > gnuplot-5.0.6.tar.gz
  - tar xzf gnuplot-5.0.6.tar.gz
  - cd gnuplot-5.0.6
  - ./configure
  - make && sudo make install-strip
  - gnuplot --version
  - cd ../
script:
  ! '[ $TRAVIS_BRANCH = bench ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    export PATH=$HOME/bin:$HOME/usr/bin:$HOME/.local/bin:$PATH &&
    cargo bench &&
    python bench_results.py &&
    git config user.email "lukas.schmierer@lschmierer.de" &&
    git config user.name "Lukas Schmierer" &&
    git add README.md &&
    git add graph/. &&
    git commit -q -m "Update benchmark results" &&
    git push -q -f https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master'
